### ISSUE TITLE
Last update doesn't work on PHP 5.6

### ISSUE THREAD

**Issue by Digitalin** [mprins/dokuwiki-plugin-openlayersmap#7]
Hi, 
I don't know if it is by design but last update of GeoPHP and Openlayersmap on server running PHP 5.6 doesn't work anymore and gives a blank page. As I understand, the coding style use type of return like : 
`public function get($key) : string` which leads multiple PHP errors like 

GeoPHP
`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/directory/lib/plugins/geophp/helper.php on line 31`

Openlayersmap 
`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/directory/lib/plugins/openlayersmap/syntax/olmap.php on line 54`

**Comment by mprins** [comment]
PHP 5.6 is no longer supported, it is EOL since 31 dec 2018, had another year of security fixes only during 2019 and is now gone. We are more than 2 years down the line and getting ready for PHP 8.

- https://www.php.net/supported-versions.php
- https://www.php.net/eol.php

The wiki page provides a link to old releases that you can download and install manually
